general {
    grace = 1
    hide_cursor = true
}

auth {
    
}

background {
    monitor = DP-2
    path = /home/tintin/.config/rofi/.current_wallpaper
}

background {
    monitor = DP-1
    path = rgb(000000)
}

background {
    monitor = HDMI-A-1
    path = rgb(000000)
}

shape {
    monitor = DP-2
    size = 500, 300
    color = rgba(0, 0, 0, 0.6)
    rounding = 20
    halign = right
    valign = bottom
    position = -50, 50
}

image {
    monitor = DP-2
    path = /var/lib/AccountsService/icons/tintin
    halign = right
    valign = bottom
    position = -223, 270
    rounding = -1
    border_size = 4
    border_color = rgb(BAC3FF)
}

label {
    monitor = DP-2
    text = $USER
    font_family = Rubix Semi bold
    font_size = 40
    halign = right
    valign = bottom
    position = -223, 190
}

label {
    monitor = DP-2
    text = cmd[update:0] echo "@$(hostname)"
    font_family = Rubix Semi bold
    font_size = 20
    color = rgb(BAC3FF)
    halign = right
    valign = bottom
    position = -175, 155
}

input-field {
    monitor = DP-2
    fade_on_empty = false
    halign = right
    valign = bottom
    placeholder_text = <i>Entrez votre Mot de Passe</i>
    font_family = Rubix Semi bold
    position = -100, 80
    size = 400, 50
    outer_color = rgb(BAC3FF)
    inner_color = rgb(11131C)
    font_color = rgb(BAC3FF)
    dots_size = 0.3
    dots_spacing = 0.4
}