config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
profiles:
  default:
    dotfiles:
    - ALL

  Ubuntu-Couillon:
    dotfiles:
    - f_bashrc
    - f_vimrc
    - ags
    - update_hypr
    - cava
    - kitty
    - rofi
    - hypr
dotfiles:
  bashrc:
    src: .bashrc
    dst: ~/.bashrc
  vimrc:
    src: .vimrc
    dst: ~/.vimrc
  update_hypr:
    src: update_hypr.sh
    dst: ~/update_hypr.sh
  ags:
    src: config/ags
    dst: ~/.config/ags
  cava:
    src: config/cava
    dst: ~/.config/cava
  kitty:
    src: config/kitty
    dst: ~/.config/kitty
  rofi:
    src: config/rofi
    dst: ~/.config/rofi
  hypr:
    src: config/hypr
    dst: ~/.config/hypr
  f_config.yaml:
    src: dots/config.yaml
    dst: ~/dots/config.yaml
  f_config.yaml_1:
    src: config.yaml
    dst: ~/config.yaml
  f_dots_save_config.yaml:
    src: dots_save/config.yaml
    dst: ~/dots_save/config.yaml
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
    chmod: '644'
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
