exec-once = /usr/lib/geoclue-2.0/demos/agent &
exec-once = gammastep &
exec-once = /home/tintin/.config/quickshell/qs_launch.sh

exec-once = fcitx5 &

exec-once = hypridle &

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
exec-once = dbus-update-activation-environment --all &
exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
exec-once = hyprpm reload &

#exec-once = gnome-keyring-daemon --start --components=secrets &
exec-once = (/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 || /usr/libexec/polkit-gnome-authentication-agent-1) &
exec-once = hypridle &
exec-once = $scriptsDir/Polkit.sh &

exec-once = wl-paste --watch cliphist store &
exec-once = wl-paste --type text --watch cliphist store &
exec-once = wl-paste --type image --watch cliphist store &

exec-once = systemctl --user start opentabletdriver.service &

exec-once = discord &
exec-once = flatpak run com.rtosta.zapzap &
exec-once = steam &
exec-once = heroic &
exec-once = openrgb --startminimized &
exec-once = /usr/bin/flatpak run com.github.iwalton3.jellyfin-mpv-shim --no-gui &
exec-once = /usr/bin/flatpak run org.chromium.Chromium --profile-directory=Default --app-id=fbejopjnaaobpcmmffngghmhcjpkplfp

# Hyprlauncher
exec-once = hyprlauncher -d

# Sound for G PRO X
exec-once = amixer -c 2 sset 'PCM' 90%

#exec-once = /usr/lib/xdg-desktop-portal-hyprland
#exec-once = /usr/lib/xdg-desktop-portal-gtk
#exec-once = bash ~/.config/quickshell/scripts/nvidia-pref.sh
